config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :reviews
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users' => 'devise/registrations#destroy'
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class="container-fluid d-flex justify-content-center">
  <h1>Welcome to JoyStikt</h1>
</div>
<!--Checking if a user is logged in-->

<% if current_user %>
  <div class="container-fluid d-flex justify-content-center">
    <p>Hello <%= current_user.fName %>!</p>
  </div>
  <div class="container-fluid d-flex justify-content-center">
  </div>
  <!--  Also checking if the logged in user is of admin role-->
  <% if current_user.admin? %>
    <%= render 'layouts/admin' %>

  <% end %>
  <div class="container-fluid d-flex justify-content-center">
    <p>
      You are successfully logged in!
    </p>
  </div>
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to "Create a new review?", new_review_path %>
  </div>

  <!--  Using destroy_user_session_path will destroy the session for the current user. Using registration instead of session will delete the user entirely-->
  <div class="container-fluid d-flex justify-content-center">

    <%= link_to "Sign Out", destroy_user_session_path, "data-turbo-method": :delete %>
  </div>
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to "Edit Account", edit_user_registration_path %>
  </div>
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to "Delete Account", user_registration_path, "data-turbo-method": :delete, data: { turbo_confirm: "Are you sure?" } %>
  </div>
<% else %>
  <div class="container-fluid d-flex justify-content-center">
    <p>You are not signed in</p>
  </div>
  <!--  Using new_user_registration_path registers a new user in the system. Using new_user_session_path will log you in for the duration of the session-->
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to "Sign Up", new_user_registration_path %>
  </div>
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to "Login", new_user_session_path %>
  </div>

<% end %>
</div>